# Generated by Django 5.2 on 2025-04-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0004_meep'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
